In [5]:
import numpy as np

arr1 = np.arange(1, 11)
print("1-10 хүртэлх массив:\n", arr1)

1-10 хүртэлх массив:
 [ 1  2  3  4  5  6  7  8  9 10]


In [6]:
import numpy as np

arr2 = np.zeros((5, 5))
print("5x5 хэмжээтэй 0-үүд:\n", arr2)

5x5 хэмжээтэй 0-үүд:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
import numpy as np

arr3 = np.ones((3, 4))
print("3x4 хэмжээтэй 1-үүд:\n", arr3)

3x4 хэмжээтэй 1-үүд:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

add_result = a + b
print("a + b = ", add_result)

a + b =  [ 6  8 10 12]


In [9]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

mul_result = a * b
print("a * b = ", mul_result)

a * b =  [ 5 12 21 32]


In [10]:
import numpy as np

a = np.array([1, 2, 3, 4])

sq_result = a ** 2
print("a-ийн квадрат = ", sq_result)

a-ийн квадрат =  [ 1  4  9 16]


In [11]:
import numpy as np

a = np.array([1, 2, 3, 4])

mean_a = np.mean(a)
sum_a = np.sum(a)
max_a = np.max(a)

print(f"a массивын дундаж: {mean_a}")
print(f"a массивын нийлбэр: {sum_a}")
print(f"a массивын хамгийн их утга: {max_a}")

a массивын дундаж: 2.5
a массивын нийлбэр: 10
a массивын хамгийн их утга: 4
