In [4]:
import numpy as np

# Өгөгдсөн массив
arr = np.array([4, 7, 2, 9, 5, 1, 8])

# Нийлбэр
print("Нийлбэр:", np.sum(arr))

# Дундаж
print("Дундаж:", np.mean(arr))

# Хамгийн их утга
print("Хамгийн их утга:", np.max(arr))

# Хамгийн бага утга
print("Хамгийн бага утга:", np.min(arr))

Нийлбэр: 36
Дундаж: 5.142857142857143
Хамгийн их утга: 9
Хамгийн бага утга: 1


In [1]:
import numpy as np

# 0-29 хүртэлх массив үүсгэх
arr = np.arange(30)

# 6x5 матриц болгох
matrix_6x5 = arr.reshape(6, 5)

# 10-аас их утгууд
greater_than_10 = arr[arr > 10]

# 3-т хуваагддаг утгууд
divisible_by_3 = arr[arr % 3 == 0]

print("6x5 матриц:")
print(matrix_6x5)

print("10-аас их утгууд:")
print(greater_than_10)

print("3-т хуваагддаг утгууд:")
print(divisible_by_3)

6x5 матриц:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
10-аас их утгууд:
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
3-т хуваагддаг утгууд:
[ 0  3  6  9 12 15 18 21 24 27]


In [5]:
import numpy as np

# Хоёр массив үүсгэх
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

# Хоёр массивыг нэгтгэх
combined_array = np.concatenate((arr1, arr2))

# 2x5 матриц болгох
matrix_2x5 = combined_array.reshape(2, 5)

print("Эхний массив:", arr1)
print("Хоёр дахь массив:", arr2)
print("Нэгтгэсэн массив:", combined_array)
print("2x5 матриц:")
print(matrix_2x5)

Эхний массив: [1 2 3 4 5]
Хоёр дахь массив: [ 6  7  8  9 10]
Нэгтгэсэн массив: [ 1  2  3  4  5  6  7  8  9 10]
2x5 матриц:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
